# Generated by Django 3.1.4 on 2021-01-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='Picture',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
    ]
